# Generated by Django 3.0.4 on 2020-04-07 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20200406_0905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='listinsg_id',
            new_name='listing_id',
        ),
    ]
